import '@/styles/globals.css'
import Footer from '@components/footer/Footer'

import Nav from '@components/navbar/Nav'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container'>
          <Nav/>
        {children}
        <Footer/>
        </div>
        
      </body>
    </html>
  )
}
